spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/School
    password: Viyaan@17
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true