##YAML Ain't Markup Language
##spring.application.name=EcomDB
##server:
##  port=9181
##spring:
##    profiles:
##     active: QA
##---
##
##spring:
##  profiles: dev
##  datasource:
##    url :
###      username :
##    username:
##    password:
##  jpa:
##    hibernate:
##      ddl-auto: create
##    database:
##      platform: org.hibernate.dialect.PostgreSQLDialect
##
##
##---
#
##spring.application.name=EcomDB
##server:
##  port: 9181
##
##
##spring:
##  datasource:
##    url: jdbc:postgresql://localhost:5432/sales
##    username: postgres
##    password: Viyaan@11
##  jpa:
##    hibernate:
##      ddl-auto: create
##    database:
##      platform: org.hibernate.dialect.PostgreSQLDialect
#
#---
#
###spring:
##  profiles: qa
#  datasource:
#    url: jdbc:postgresql://localhost:5432/your_database_name
#    username: your_username
#    password: your_password
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database:
# #     platform: org.hibernate.dialect.PostgreSQLDialect


#database:
#  type: postgres
#  username: postgres
#  password: Viyaan@11
#  url: jdbc:postgresql://localhost:5432/sales
#  platform: org.hibernate.dialect.PostgreSQLDialect
#  ddl : create-drop

---
#Spring:
#  profiles: QA
#database:
#  type: postgres
#  username: postgres
#  password: Viyaan@11
#  url: jdbc:postgresql://localhost:5432/sales-QA
#  platform: org.hibernate.dialect.PostgreSQLDialect
#  ddl : create-drop

---
#Spring:
#  profiles: prod
#database:
#  type: postgres
#  username: postgres
#  password: Viyaan@11
#  url: jdbc:postgresql://localhost:5432/sales-prod
#  platform: org.hibernate.dialect.PostgreSQLDialect
#  ddl : create-drop

---
#QA
#Prod
#Dev

#logging:
#  level: INFO
#  file : /var/log/myapp.log








